<?php

namespace Database\Seeders;

use Illuminate\Support\Str;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PropertiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('properties')->insert([
            ['suburb' => 'Parramatta', 'state' => 'NSW', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Parramatta', 'state' => 'NSW', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Parramatta', 'state' => 'NSW', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Parramatta', 'state' => 'NSW', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Parramatta', 'state' => 'NSW', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Parramatta', 'state' => 'NSW', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Parramatta', 'state' => 'NSW', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Parramatta', 'state' => 'NSW', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Parramatta', 'state' => 'NSW', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Parramatta', 'state' => 'NSW', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Parramatta', 'state' => 'NSW', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Parramatta', 'state' => 'NSW', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Parramatta', 'state' => 'NSW', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Parramatta', 'state' => 'NSW', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Ryde', 'state' => 'NSW', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Ryde', 'state' => 'NSW', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Ryde', 'state' => 'NSW', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Ryde', 'state' => 'NSW', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Ryde', 'state' => 'NSW', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Castle Hill', 'state' => 'NSW', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Richmond', 'state' => 'NSW', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Richmond', 'state' => 'NSW', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Richmond', 'state' => 'NSW', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Richmond', 'state' => 'NSW', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Richmond', 'state' => 'NSW', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Richmond', 'state' => 'NSW', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Richmond', 'state' => 'NSW', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Richmond', 'state' => 'NSW', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Richmond', 'state' => 'NSW', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Richmond', 'state' => 'NSW', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Richmond', 'state' => 'NSW', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Richmond', 'state' => 'NSW', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Richmond', 'state' => 'NSW', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Richmond', 'state' => 'NSW', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Richmond', 'state' => 'NSW', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Richmond', 'state' => 'NSW', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Southbank', 'state' => 'Qld', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Southbank', 'state' => 'Qld', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Southbank', 'state' => 'Qld', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Southbank', 'state' => 'Qld', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Southbank', 'state' => 'Qld', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Southbank', 'state' => 'Qld', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Southbank', 'state' => 'Qld', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Southbank', 'state' => 'Qld', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Southbank', 'state' => 'Qld', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Southbank', 'state' => 'Qld', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Southbank', 'state' => 'Qld', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Southbank', 'state' => 'Qld', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'O\'Sullivan Beach', 'state' => 'Qld', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'O\'Sullivan Beach', 'state' => 'Qld', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'O\'Sullivan Beach', 'state' => 'Qld', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'O\'Sullivan Beach', 'state' => 'Qld', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'O\'Sullivan Beach', 'state' => 'Qld', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'O\'Sullivan Beach', 'state' => 'Qld', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'O\'Sullivan Beach', 'state' => 'Qld', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'O\'Sullivan Beach', 'state' => 'Qld', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Geelong', 'state' => 'Vic', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Geelong', 'state' => 'Vic', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Geelong', 'state' => 'Vic', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Geelong', 'state' => 'Vic', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Geelong', 'state' => 'Vic', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Geelong', 'state' => 'Vic', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Geelong', 'state' => 'Vic', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Geelong', 'state' => 'Vic', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Geelong', 'state' => 'Vic', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Geelong', 'state' => 'Vic', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Geelong', 'state' => 'Vic', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Geelong', 'state' => 'Vic', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Geelong', 'state' => 'Vic', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Geelong', 'state' => 'Vic', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Geelong', 'state' => 'Vic', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Geelong', 'state' => 'Vic', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Fitzroy', 'state' => 'Vic', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Richmond', 'state' => 'Vic', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Richmond', 'state' => 'Vic', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Richmond', 'state' => 'Vic', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Richmond', 'state' => 'Vic', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Richmond', 'state' => 'Vic', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Richmond', 'state' => 'Vic', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Richmond', 'state' => 'Vic', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Richmond', 'state' => 'Vic', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Richmond', 'state' => 'Vic', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Richmond', 'state' => 'Vic', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Richmond', 'state' => 'Vic', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Richmond', 'state' => 'Vic', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Richmond', 'state' => 'Vic', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Richmond', 'state' => 'Vic', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Richmond', 'state' => 'Vic', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Richmond', 'state' => 'Vic', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Richmond', 'state' => 'Vic', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Richmond', 'state' => 'Vic', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Richmond', 'state' => 'Vic', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Subiaco', 'state' => 'WA', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Subiaco', 'state' => 'WA', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Subiaco', 'state' => 'WA', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Subiaco', 'state' => 'WA', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Subiaco', 'state' => 'WA', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Subiaco', 'state' => 'WA', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Subiaco', 'state' => 'WA', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],
            ['suburb' => 'Subiaco', 'state' => 'WA', 'country' => 'Australia', 'guid' => Str::uuid(), 'created_at'=>date('Y-m-d H:i:s'), 'updated_at'=>date('Y-m-d H:i:s'),],

        ]);
    }
}
